[workspace]
default-members = ["nome"]
members = ["nome", "nome-android"]

resolver = "2"

[workspace.metadata.cargo-machete]
ignored = []

[workspace.dependencies]
tokio = "1.38"

mnomer = { path = "../forks/mnomer" }
test-engine = { path = "../test-engine/test-engine" }

nome = { path = "nome" }
