[workspace]

# default-members = ["level-test"]
#default-members = ["ui-test"]
default-members = ["test-game"]
members = [
  "test-engine",
  "test-game",
  "test-game-android",
  "ui-test",
  "ui-benchmark",
  "level-test",
  "deps/ui/ui-proc-test",
  "sand",
]

resolver = "2"

[workspace.metadata.cargo-machete]
ignored = []

[workspace.dependencies]
android_logger = "0.14"
anyhow = "1.0"
bytemuck = { version = "1.15", features = ["derive"] }
cfg_aliases = "0.2"
chrono = "0.4"
convert_case = "0.6"
dirs = "5.0"
educe = "0.6.0"
env_logger = "0.11"
fake = "2.9.2"
home = "0.5"
image = "0.25"
log = "0.4"
nonempty = "0.10.0"
quote = "1.0"
rand = "0.8"
rapier2d = { version = "0.21", features = ["simd-stable"] }
#rapier2d = { version = "0.20.0", features = ["enhanced-determinism"] }
# rapier2d = { version = "0.20.0", features = ["parallel", "simd-stable"] }
lyon = "1.0"
rodio = "0.19.0"
rust_decimal = "1.35"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serial_test = "3.1"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls"] }
syn = { version = "2.0", features = ["full", "extra-traits"] }
tokio = { version = "1.38.0", features = ["full"] }
web-time = "1.0.0"

glyph_brush = "0.7.8"
wgpu = "0.20.1"
wgpu_text = "0.8.8"
winit = "0.30.1"

manage = "=0.6.0"
reflected = "=0.10.1"
refs = { version = "=0.11.0", default-features = true }
tain = "=0.3.0"
vents = "=0.6.0"

audio = { path = "deps/audio" }
call_counter = { path = "deps/call_counter" }
dispatch = { path = "deps/dispatch" }
gen = { path = "deps/gen" }
gm = { path = "deps/gm" }
level = { path = "deps/level" }
level-proc = { path = "deps/level/level-proc" }
store = { path = "deps/store" }
test-engine = { path = "test-engine" }
test-game = { path = "test-game" }
ui = { path = "deps/ui" }
ui-benchmark = { path = "ui-benchmark" }
ui-proc = { path = "deps/ui/ui-proc" }
utils = { path = "deps/utils" }
valid = { path = "deps/valid" }
wgpu_wrapper = { path = "deps/wgpu_wrapper" }

[patch.crates-io]
#wgpu = { git = "https://github.com/VladasZ/wgpu", rev = "b2cc37132280e34cdd906a5939b8c472406704f7" }
#wgpu = { path = "../3/wgpu/wgpu" }
#vents = { path = "../deps/vents/vents" }
#reflected = { path = "../deps/reflected/reflected" }
#tain = { path = "../deps/tain/tain" }
