[package]
edition = "2021"
name = "sand"
version = "0.1.0"

[[bin]]
name = "sand"
path = "src/main.rs"


[dependencies]
anyhow = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }

tain = { workspace = true }
