[package]
authors.workspace = true
edition.workspace = true
name = "nome"
version.workspace = true

[[bin]]
name = "nome"

[lib]
crate-type = ["rlib", "staticlib"]
name = "nome"

[dependencies]
mnomer = { workspace = true }
test-engine = { workspace = true }

[build-dependencies]
plat = { workspace = true }

[lints]
workspace = true
