[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "nome"
version = "0.1.0"

[[bin]]
name = "nome"

[lib]
crate-type = ["rlib", "staticlib"]
name = "nome"

[dependencies]
tokio = { workspace = true }

test-engine = { workspace = true }
