[package]
authors.workspace = true
edition.workspace = true
name = "nome-android"
version.workspace = true

[lib]
crate-type = ["cdylib"]
name = "nome"

[dependencies]
nome = { workspace = true }
hilen = { workspace = true }

[package.metadata.android]
build_targets = ["armv7-linux-androideabi", "aarch64-linux-android"]
min_sdk_version = 23
target_sdk_version = 29

[lints]
workspace = true
