[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2021"
name = "audio"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "audio"

[dependencies]
log = { workspace = true }
manage = { workspace = true }

rodio = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }
