[target.aarch64-linux-android]
ar = "ndk/bin/aarch64-linux-android-ar"
linker = "ndk/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "ndk/bin/armv7a-linux-androideabi-ar"
linker = "ndk/bin/armv7a-linux-androideabi21-clang"

[target.i686-linux-android]
ar = "ndk/bin/i686-linux-android-ar"
linker = "ndk/bin/i686-linux-android21-clang"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=off"]

[target.aarch64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=off"]

[profile.size]
inherits = "release-plus"
opt-level = "z"

[profile.release-debug]
debug = true
inherits = "release"

[profile.r2]
inherits = "release"
#debug = true
lto = "fat"
strip = true

[profile.r3]
codegen-units = 1
inherits = "release"
strip = true
#opt-level = "z"
debug = false
lto = "fat"
#panic = "abort"
overflow-checks = false

[profile.profile]
codegen-units = 1
debug = "full"
inherits = "dev"
lto = "off"
opt-level = 0
strip = false

#[profile.dev.package."*"]
#opt-level = 3
